Homework2
Awootsim/Learning pull request #22
Opened 2023-06-05 16:39 UTC by Awootsim

2023-06-08 12:01 UTC, maksim-obodkov commented on Lesson 9/task_2(2).py
> +def func1():
нет doc_string func1 и func2

2023-06-08 12:01 UTC, maksim-obodkov commented on Lesson 9/task_2(2).py
> +def func_log(file_log='log.txt'):
pep8 нужно 2 пустых строки перед методом

2023-06-08 12:01 UTC, maksim-obodkov commented on Lesson 9/task_2(2).py
> +@func_log(file_log='func2.txt')
pep8 нужно 2 пустых строки перед методом

2023-06-08 12:02 UTC, maksim-obodkov commented on Lesson 9/task_2(2).py
> +func1()
pep8 нужно 2 пустых строки после метода

2023-06-08 12:04 UTC, maksim-obodkov commented on Lesson 9/task_3(1).py
> +three_most_expensive_purchases = find_three_most_expensive_purchases(filename)
Если честно - очень сложно 
есть функция readlines() она бы избавила тебя от .split()

+ можно было не записывать решение в функцию с return, а просто без def читать файл и в фор считать сумму через +=

2023-06-08 12:04 UTC, maksim-obodkov commented on Lesson 9/task_3(1).py
> +    prices.sort(reverse=True)
pep8 2 строки пробела, можно только одну

2023-06-08 12:04 UTC, maksim-obodkov commented on Lesson 9/task_3(1).py
> +filename = 'test_file/task_3.txt'
pep8 одна строка пробела после функции, нужно две

2023-06-11 19:46 UTC, vlad-vladimirovich requested changes

2023-06-11 19:46 UTC, vlad-vladimirovich commented on Lesson_10/task1.py
> +        word1 = ''.join(random.choices(string.ascii_lowercase, k=random.randint(1, 15)))
не самый хороший паттерн объявлять переменную внутри цикла

2023-06-13 16:02 UTC, merged